# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gloader < Formula
  desc "gloader is database data migration tool from any source to any destination"
  homepage "https://github.com/mohammadv184/gloader"
  version "0.1.0-dev.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mohammadv184/gloader/releases/download/v0.1.0-dev.2/gloader-0.1.0-dev.2-darwin-arm64.tar.gz"
      sha256 "e441dba53f9cbe15fb4444e63cb9b588822c71c3f82e07a63f1aebf43a56c9cf"

      def install
        bin.install "gloader"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mohammadv184/gloader/releases/download/v0.1.0-dev.2/gloader-0.1.0-dev.2-darwin-amd64.tar.gz"
      sha256 "821aabc93b3705abf8dee8fdad0aa3481f17ea0151d9504c3e02e884acff16e3"

      def install
        bin.install "gloader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mohammadv184/gloader/releases/download/v0.1.0-dev.2/gloader-0.1.0-dev.2-linux-armv6.tar.gz"
      sha256 "1325e546022e72d7ff7946a768b33ad0ec682cb1257ced2edb86474a067d2258"

      def install
        bin.install "gloader"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mohammadv184/gloader/releases/download/v0.1.0-dev.2/gloader-0.1.0-dev.2-linux-amd64.tar.gz"
      sha256 "9f625a1709d4c5aa408491ffc8f28f5c7b9cf86c9a86510f639944f28aa6bc8e"

      def install
        bin.install "gloader"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohammadv184/gloader/releases/download/v0.1.0-dev.2/gloader-0.1.0-dev.2-linux-arm64.tar.gz"
      sha256 "e26269c34007538e2b7d7258293335ca2197b8007d1645ba33d5b3991d9501bb"

      def install
        bin.install "gloader"
      end
    end
  end

  test do
    system "#{bin}/gloader", "version"
  end
end
