# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gloader < Formula
  desc "gloader is database data migration tool from any source to any destination"
  homepage "https://github.com/mohammadv184/gloader"
  version "0.1.0-dev.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mohammadv184/gloader/releases/download/v0.1.0-dev.10/gloader-0.1.0-dev.10-darwin-arm64.tar.gz"
      sha256 "20d5c96534f807ab26a3d73139ce85aae33ff61a112102a791faa54f81d7b8d3"

      def install
        bin.install "gloader"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mohammadv184/gloader/releases/download/v0.1.0-dev.10/gloader-0.1.0-dev.10-darwin-amd64.tar.gz"
      sha256 "997f72e39afff06aa59e994ea7c781904bac5f4abd4c9791b4211e7ffdf3b231"

      def install
        bin.install "gloader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mohammadv184/gloader/releases/download/v0.1.0-dev.10/gloader-0.1.0-dev.10-linux-amd64.tar.gz"
      sha256 "44d9156a40468092b0a83c95f8d1861be65bfe26916d78d74c3ad6c652541e51"

      def install
        bin.install "gloader"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohammadv184/gloader/releases/download/v0.1.0-dev.10/gloader-0.1.0-dev.10-linux-arm64.tar.gz"
      sha256 "818ecb9f15f27df1f8e5f68cf862654fa952502ce6c4c0c9e103bf643ecb7b12"

      def install
        bin.install "gloader"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mohammadv184/gloader/releases/download/v0.1.0-dev.10/gloader-0.1.0-dev.10-linux-armv6.tar.gz"
      sha256 "3f8511165ec8bc52768c00c630e1f49e1144cfad1f4e340b90c037585b2ea117"

      def install
        bin.install "gloader"
      end
    end
  end

  test do
    system "#{bin}/gloader", "version"
  end
end
