# This file was generated by GoReleaser. DO NOT EDIT.
cask "skm" do
  name "skm"
  desc "A CLI for managing FIDO2 security keys."
  homepage "https://github.com/mohammadv184/skm"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skm"
  manpage "./assets/mandocs/skm.1.gz"
  bash_completion "./assets/auto-completions/goreleaser.bash"
  zsh_completion "./assets/auto-completions/goreleaser.zsh"
  fish_completion "./assets/auto-completions/goreleaser.fish"

  on_macos do
    on_intel do
      url "https://github.com/mohammadv184/skm/releases/download/v#{version}/SKM-#{version}-darwin-amd64.tar.gz"
      sha256 "2f258aad70f2ccaa91542fef4bd92a05699e4682f6bd0cf56793743e14c9c134"
    end
    on_arm do
      url "https://github.com/mohammadv184/skm/releases/download/v#{version}/SKM-#{version}-darwin-arm64.tar.gz"
      sha256 "6b8811dbe130c088db548f0c4975dde1005c9cf88cb523cd81cf46baa78f5f0b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mohammadv184/skm/releases/download/v#{version}/SKM-#{version}-linux-amd64.tar.gz"
      sha256 "372af9e61bdfd7f309be13c236c13a33905fe576c6f845a74a06650ef60df353"
    end
    on_arm do
      url "https://github.com/mohammadv184/skm/releases/download/v#{version}/SKM-#{version}-linux-arm64.tar.gz"
      sha256 "5c494e08e2a243a247a15e923d96f3ad4c4eadf0d3c87742fb67e037d0913c95"
    end
  end

  # No zap stanza required
end
