# This file was generated by GoReleaser. DO NOT EDIT.
cask "skm" do
  name "skm"
  desc "A CLI for managing FIDO2 security keys."
  homepage "https://github.com/mohammadv184/skm"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skm"
  manpage "./assets/mandocs/skm.1.gz"
  bash_completion "./assets/auto-completions/goreleaser.bash"
  zsh_completion "./assets/auto-completions/goreleaser.zsh"
  fish_completion "./assets/auto-completions/goreleaser.fish"

  on_macos do
    on_intel do
      url "https://github.com/mohammadv184/skm/releases/download/v#{version}/SKM-#{version}-darwin-amd64.tar.gz"
      sha256 "8acdb09c4235e613513c9a13bec7cbad1bdc3f0bca81232d498a49c5718545b3"
    end
    on_arm do
      url "https://github.com/mohammadv184/skm/releases/download/v#{version}/SKM-#{version}-darwin-arm64.tar.gz"
      sha256 "0a779685279a70e0f7033d4115761eccc5425966e7feb9ebaa4b86fa573522c4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mohammadv184/skm/releases/download/v#{version}/SKM-#{version}-linux-amd64.tar.gz"
      sha256 "e617f8ff65ef3bf9ee853dfbea67c1a38f565c1b2d93b162081374a6d3ed7ec3"
    end
    on_arm do
      url "https://github.com/mohammadv184/skm/releases/download/v#{version}/SKM-#{version}-linux-arm64.tar.gz"
      sha256 "7e6ec571981623fb6c3b20ec30db3cd904240536e04445636f9da20cc24ad70b"
    end
  end

  # No zap stanza required
end
