# This file was generated by GoReleaser. DO NOT EDIT.
cask "skm" do
  name "skm"
  desc "A CLI for managing FIDO2 security keys."
  homepage "https://github.com/mohammadv184/skm"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skm"
  manpage "assets/mandocs/skm.1.gz"
  bash_completion "assets/auto-completions/goreleaser.bash"
  zsh_completion "assets/auto-completions/goreleaser.zsh"
  fish_completion "assets/auto-completions/goreleaser.fish"

  on_macos do
    on_intel do
      url "https://github.com/mohammadv184/skm/releases/download/v#{version}/skm-#{version}-darwin-amd64.tar.gz"
      sha256 "6787a46fe928989d34ed4b9ec1280b2b4423b5fcbed51ddca380973bf23e7ea5"
    end
    on_arm do
      url "https://github.com/mohammadv184/skm/releases/download/v#{version}/skm-#{version}-darwin-arm64.tar.gz"
      sha256 "ef4bdb43c2fd51a8bf13bd835931bb92a6b9345796ce077f4d9aaba72f8d1066"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mohammadv184/skm/releases/download/v#{version}/skm-#{version}-linux-amd64.tar.gz"
      sha256 "4f488cd1a0d99649205d4dfc7fadb1ace69bd63a11de5eafdb79ebe191e734c3"
    end
    on_arm do
      url "https://github.com/mohammadv184/skm/releases/download/v#{version}/skm-#{version}-linux-arm64.tar.gz"
      sha256 "2a9fcc89b97ef3aeda9e0f9c6e7f1612d65d3b952448ba29fa9f5cb621c112e2"
    end
  end

  # No zap stanza required
end
